// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: squareline_project_test_lcd

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen1
extern void ui_screen1_screen_init(void);
extern void ui_screen1_screen_destroy(void);
extern lv_obj_t *ui_screen1;
extern lv_obj_t *ui_image_logo;
// CUSTOM VARIABLES
extern lv_obj_t *uic_image_logo;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

