// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: squareline_project_test_lcd

#include "../ui.h"

lv_obj_t *uic_image_logo;
lv_obj_t *ui_screen1 = NULL;lv_obj_t *ui_image_logo = NULL;
// event funtions

// build funtions

void ui_screen1_screen_init(void)
{
ui_screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_image_logo = lv_image_create(ui_screen1);
lv_image_set_src(ui_image_logo, &ui_img_logo_frame_00_png);
lv_obj_set_width( ui_image_logo, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_image_logo, LV_SIZE_CONTENT);   /// 178
lv_obj_set_align( ui_image_logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_image_logo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_image_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_image_logo = ui_image_logo;

}

void ui_screen1_screen_destroy(void)
{
   if (ui_screen1) lv_obj_del(ui_screen1);

// NULL screen variables
ui_screen1= NULL;
uic_image_logo= NULL;
ui_image_logo= NULL;

}
