' MODULE WIFI
' 9/21/25

@startuml

title MODULE_WIFI

skinparam dpi 400


actor "TASK" as TASK
participant "MODULE_WIFI\nSTATE\nIDLE" as MW_IDLE
participant "MODULE_WIFI\nSTATE\nPROVISIONED" as MW_PROVISIONED
participant "MODULE_WIFI\nSTATE\nCONNECT_DEFAULT" as MW_CONNECT_DEFAULT
participant "MODULE_WIFI\nSTATE\nPROVISION_SMARTCONFIG" as MW_PROVISION_SMARTCONFIG
participant "MODULE_WIFI\nSTATE\nCONNECTING" as MW_CONNECTING
participant "MODULE_WIFI\nSTATE\nCONNECTED" as MW_CONNECTED
participant "MODULE_WIFI\nSTATE\nDISCONNECTING" as MW_DISCONNECTING
participant "MODULE_WIFI\nSTATE\nDISCONNECT" as MW_DISCONNECTED

TASK -> MW_IDLE: Initial state set to IDLE


box "DRIVER WIFI" #LightGreen
participant "STATE\nCONNECTED\n" as DW_CONNECTED
participant "STATE\nDISCONNECTED\n" as DW_DISCONNECTED
end box


DW_IDLE -> DW_DISCONNECTED: Initial set state to DISCONNECTED

MW -> DW_DISCONNECTED : <color #FF00FF>DRIVER_WIFI_Connect()</color>
activate DW_DISCONNECTED
DW_DISCONNECTED -> DW_DISCONNECTED : <color #0000FF>esp_wifi_start()</color>
return

ESP_WIFIEVENT -> DW_DISCONNECTED : WIFI_EVENT_STA_DISCONNECTED
ESP_WIFIEVENT -> ESP_WIFIEVENT : WIFI_EVENT_STA_START\n<color #0000FF>esp_wifi_connect()</color>

ESP_IPEVENT -> DW_CONNECTED : IP_EVENT_STA_GOT_IP
ESP_IPEVENT -> ESP_IPEVENT : IP_EVENT_STA_LOST_IP\n<color #0000FF>DRIVER_WIFI_Disconnect()</color>

MW -> DW_CONNECTED : <color #FF00FF>DRIVER_WIFI_Disconnect()</color>
activate DW_CONNECTED
DW_CONNECTED -> DW_CONNECTED : <color #0000FF>esp_wifi_disconnect()</color>
return

@enduml
