// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: squareline_project_test_lcd

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_anim_t * animationlogo_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t *ui_imgset_frame_[59] = {&ui_img_logo_frame_00_png, &ui_img_logo_frame_01_png, &ui_img_logo_frame_02_png, &ui_img_logo_frame_03_png, &ui_img_logo_frame_04_png, &ui_img_logo_frame_05_png, &ui_img_logo_frame_06_png, &ui_img_logo_frame_07_png, &ui_img_logo_frame_08_png, &ui_img_logo_frame_09_png, &ui_img_logo_frame_10_png, &ui_img_logo_frame_11_png, &ui_img_logo_frame_12_png, &ui_img_logo_frame_13_png, &ui_img_logo_frame_14_png, &ui_img_logo_frame_15_png, &ui_img_logo_frame_16_png, &ui_img_logo_frame_17_png, &ui_img_logo_frame_18_png, &ui_img_logo_frame_19_png, &ui_img_logo_frame_20_png, &ui_img_logo_frame_21_png, &ui_img_logo_frame_22_png, &ui_img_logo_frame_23_png, &ui_img_logo_frame_24_png, &ui_img_logo_frame_25_png, &ui_img_logo_frame_26_png, &ui_img_logo_frame_27_png, &ui_img_logo_frame_28_png, &ui_img_logo_frame_29_png, &ui_img_logo_frame_30_png, &ui_img_logo_frame_31_png, &ui_img_logo_frame_32_png, &ui_img_logo_frame_33_png, &ui_img_logo_frame_34_png, &ui_img_logo_frame_35_png, &ui_img_logo_frame_36_png, &ui_img_logo_frame_37_png, &ui_img_logo_frame_38_png, &ui_img_logo_frame_39_png, &ui_img_logo_frame_40_png, &ui_img_logo_frame_41_png, &ui_img_logo_frame_42_png, &ui_img_logo_frame_43_png, &ui_img_logo_frame_44_png, &ui_img_logo_frame_45_png, &ui_img_logo_frame_46_png, &ui_img_logo_frame_47_png, &ui_img_logo_frame_48_png, &ui_img_logo_frame_49_png, &ui_img_logo_frame_50_png, &ui_img_logo_frame_51_png, &ui_img_logo_frame_52_png, &ui_img_logo_frame_53_png, &ui_img_logo_frame_54_png, &ui_img_logo_frame_55_png, &ui_img_logo_frame_56_png, &ui_img_logo_frame_57_png, &ui_img_logo_frame_58_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
lv_anim_t * animationlogo_Animation( lv_obj_t *TargetObject, int delay)
{
lv_anim_t *out_anim;
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_frame_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_frame_)/(sizeof(lv_image_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 5000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame );
lv_anim_set_values(&PropertyAnimation_0, 1, 58 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 1);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame );
out_anim = lv_anim_start(&PropertyAnimation_0);

return out_anim;
}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screen1);
}

void ui_destroy( void )
{ui_screen1_screen_destroy();
}
