// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: squareline_project_test_lcd

#ifndef _SQUARELINE_PROJECT_TEST_LCD_UI_H
#define _SQUARELINE_PROJECT_TEST_LCD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_screen1.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * animationlogo_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_logo_frame_00_png);   // assets/logo/frame_00.png
LV_IMG_DECLARE( ui_img_logo_frame_01_png);   // assets/logo/frame_01.png
LV_IMG_DECLARE( ui_img_logo_frame_02_png);   // assets/logo/frame_02.png
LV_IMG_DECLARE( ui_img_logo_frame_03_png);   // assets/logo/frame_03.png
LV_IMG_DECLARE( ui_img_logo_frame_04_png);   // assets/logo/frame_04.png
LV_IMG_DECLARE( ui_img_logo_frame_05_png);   // assets/logo/frame_05.png
LV_IMG_DECLARE( ui_img_logo_frame_06_png);   // assets/logo/frame_06.png
LV_IMG_DECLARE( ui_img_logo_frame_07_png);   // assets/logo/frame_07.png
LV_IMG_DECLARE( ui_img_logo_frame_08_png);   // assets/logo/frame_08.png
LV_IMG_DECLARE( ui_img_logo_frame_09_png);   // assets/logo/frame_09.png
LV_IMG_DECLARE( ui_img_logo_frame_10_png);   // assets/logo/frame_10.png
LV_IMG_DECLARE( ui_img_logo_frame_11_png);   // assets/logo/frame_11.png
LV_IMG_DECLARE( ui_img_logo_frame_12_png);   // assets/logo/frame_12.png
LV_IMG_DECLARE( ui_img_logo_frame_13_png);   // assets/logo/frame_13.png
LV_IMG_DECLARE( ui_img_logo_frame_14_png);   // assets/logo/frame_14.png
LV_IMG_DECLARE( ui_img_logo_frame_15_png);   // assets/logo/frame_15.png
LV_IMG_DECLARE( ui_img_logo_frame_16_png);   // assets/logo/frame_16.png
LV_IMG_DECLARE( ui_img_logo_frame_17_png);   // assets/logo/frame_17.png
LV_IMG_DECLARE( ui_img_logo_frame_18_png);   // assets/logo/frame_18.png
LV_IMG_DECLARE( ui_img_logo_frame_19_png);   // assets/logo/frame_19.png
LV_IMG_DECLARE( ui_img_logo_frame_20_png);   // assets/logo/frame_20.png
LV_IMG_DECLARE( ui_img_logo_frame_21_png);   // assets/logo/frame_21.png
LV_IMG_DECLARE( ui_img_logo_frame_22_png);   // assets/logo/frame_22.png
LV_IMG_DECLARE( ui_img_logo_frame_23_png);   // assets/logo/frame_23.png
LV_IMG_DECLARE( ui_img_logo_frame_24_png);   // assets/logo/frame_24.png
LV_IMG_DECLARE( ui_img_logo_frame_25_png);   // assets/logo/frame_25.png
LV_IMG_DECLARE( ui_img_logo_frame_26_png);   // assets/logo/frame_26.png
LV_IMG_DECLARE( ui_img_logo_frame_27_png);   // assets/logo/frame_27.png
LV_IMG_DECLARE( ui_img_logo_frame_28_png);   // assets/logo/frame_28.png
LV_IMG_DECLARE( ui_img_logo_frame_29_png);   // assets/logo/frame_29.png
LV_IMG_DECLARE( ui_img_logo_frame_30_png);   // assets/logo/frame_30.png
LV_IMG_DECLARE( ui_img_logo_frame_31_png);   // assets/logo/frame_31.png
LV_IMG_DECLARE( ui_img_logo_frame_32_png);   // assets/logo/frame_32.png
LV_IMG_DECLARE( ui_img_logo_frame_33_png);   // assets/logo/frame_33.png
LV_IMG_DECLARE( ui_img_logo_frame_34_png);   // assets/logo/frame_34.png
LV_IMG_DECLARE( ui_img_logo_frame_35_png);   // assets/logo/frame_35.png
LV_IMG_DECLARE( ui_img_logo_frame_36_png);   // assets/logo/frame_36.png
LV_IMG_DECLARE( ui_img_logo_frame_37_png);   // assets/logo/frame_37.png
LV_IMG_DECLARE( ui_img_logo_frame_38_png);   // assets/logo/frame_38.png
LV_IMG_DECLARE( ui_img_logo_frame_39_png);   // assets/logo/frame_39.png
LV_IMG_DECLARE( ui_img_logo_frame_40_png);   // assets/logo/frame_40.png
LV_IMG_DECLARE( ui_img_logo_frame_41_png);   // assets/logo/frame_41.png
LV_IMG_DECLARE( ui_img_logo_frame_42_png);   // assets/logo/frame_42.png
LV_IMG_DECLARE( ui_img_logo_frame_43_png);   // assets/logo/frame_43.png
LV_IMG_DECLARE( ui_img_logo_frame_44_png);   // assets/logo/frame_44.png
LV_IMG_DECLARE( ui_img_logo_frame_45_png);   // assets/logo/frame_45.png
LV_IMG_DECLARE( ui_img_logo_frame_46_png);   // assets/logo/frame_46.png
LV_IMG_DECLARE( ui_img_logo_frame_47_png);   // assets/logo/frame_47.png
LV_IMG_DECLARE( ui_img_logo_frame_48_png);   // assets/logo/frame_48.png
LV_IMG_DECLARE( ui_img_logo_frame_49_png);   // assets/logo/frame_49.png
LV_IMG_DECLARE( ui_img_logo_frame_50_png);   // assets/logo/frame_50.png
LV_IMG_DECLARE( ui_img_logo_frame_51_png);   // assets/logo/frame_51.png
LV_IMG_DECLARE( ui_img_logo_frame_52_png);   // assets/logo/frame_52.png
LV_IMG_DECLARE( ui_img_logo_frame_53_png);   // assets/logo/frame_53.png
LV_IMG_DECLARE( ui_img_logo_frame_54_png);   // assets/logo/frame_54.png
LV_IMG_DECLARE( ui_img_logo_frame_55_png);   // assets/logo/frame_55.png
LV_IMG_DECLARE( ui_img_logo_frame_56_png);   // assets/logo/frame_56.png
LV_IMG_DECLARE( ui_img_logo_frame_57_png);   // assets/logo/frame_57.png
LV_IMG_DECLARE( ui_img_logo_frame_58_png);   // assets/logo/frame_58.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
